apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/softwareengineerva/gke.git
    targetRevision: HEAD
    path: k8s-manifests/backend-api/base
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
