apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-demo-sa
  namespace: secrets-demo
  annotations:
    iam.gke.io/gcp-service-account: concur-test-test-app@shc-labs.iam.gserviceaccount.com
