apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets
  namespace: postgres
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/shc-labs/secrets/concur-test-postgres-creds/versions/latest"
        fileName: "concur-test-postgres-credentials"
  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: concur-test-postgres-credentials
          key: username
        - objectName: concur-test-postgres-credentials
          key: password
        - objectName: concur-test-postgres-credentials
          key: database
