apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets
  namespace: postgres
  labels:
    app: postgres
    env: dev
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/shc-labs/secrets/concur-test-postgres-user/versions/latest"
        path: "username"
      - resourceName: "projects/shc-labs/secrets/concur-test-postgres-pass/versions/latest"
        path: "password"
      - resourceName: "projects/shc-labs/secrets/concur-test-postgres-db/versions/latest"
        path: "database"
  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: database
          key: database
