apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: postgres
  annotations:
    iam.gke.io/gcp-service-account: concur-test-postgres-sa@my-gcp-project.iam.gserviceaccount.com
